name: ci-golang
on: 
  pull_request:
    branches:
    - develop 

jobs: 
  check-application:
    strategy:
      matrix:
        go: ['1.14','1.15']
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - uses:  actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      -name: run the test    
      - run: go test
      -name: run the application
      - run: go run math.go

      -name: set up QMUE
      -uses: docker/setup-qemu-action@v1

      -name: set up Docker Buildx
      -uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: gabrielmonzato/goci:latest